---
layout: post
title: "Since We Made It Here We Can Make It Anywhere"
image_thumbnail_500x320: "since-we-made-it-here-we-can-make-it-anywhere-ILoveYouVanx320.JPG"
image_thumbnail_500x500: "since-we-made-it-here-we-can-make-it-anywhere-ILoveYouVanx500.JPG"
categories: [life]
tags: [family, nyc]
---  
<p>After nearly two years in NYC our time has finally come to an end.&nbsp; During this time we have been all over the city soaking in everything it has to offer.&nbsp; As we reflect on our time there, we realize just how much we have accomplished and how thankful we are to have had the chance to experience it first hand. New York is a fascinating place filled with big dreams, and even bigger egos.&nbsp; You have to have guts to survive here, and if you have never lived in a major city, amateurs will get eaten alive rapidly.&nbsp; We were lucky enough to have a corporation move us to try it out and living at 83rd and Columbus on the Upper West Side next to the park definitely made things easier.&nbsp; Numerous songs have been written about each of the five boroughs, but this is our take on the experiences we shared.&nbsp;</p>
<!-- more -->
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-ILoveYouVan.JPG %}</p>
<p>Let&rsquo;s start with the food.&nbsp; With all the cultures of the world blending together it kinda feels like going around the world in Epcot Center, Disney World, but it&rsquo;s the real deal.&nbsp; NYC definitely has the most international feel out of any U.S. city we have lived in.&nbsp; Some of our favorite places include: Cafe Frida {Mexican}, Jacob&rsquo;s Pickles {American heritage} Tacombi {Mexican}, Russ and Daughters {Jewish Deli}, Katz Deli {Jewish Deli}, Sarabeth&rsquo;s {American}, The Spotted Big {British Gastropub}, The Breslin {British Gastropub}, Nobu {Japanese}, Quality Meats {Steakhouse}, Korzo Haus {Czech}, and Keste {Neapolitan Pizza}.</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-table.JPG %}</p>
<p>When we not getting fat out on the town, we stocked up on ingredients at some of our favorite food purveyors: Dickson&rsquo;s Farmstand {butcher},&nbsp; Lucy&rsquo;s Whey {artisan cheeses}, Jacques Torres Chocolate, The Lobster Pound, Amy&rsquo;s Bread, and the Union Square Green Market.&nbsp; Although our kitchen would most likely fit in your bathroom, it was actually quite large for NYC city standards.&nbsp; We took advantage of our &ldquo;enormous space&rdquo; as one of the very few families who actually took the time to cook for ourselves. &nbsp;</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-Painting.JPG %}</p>
<p>Outside of filling our stomachs, we loved visiting the MOMA, the Met, the Guggenheim, and the Museum of Natural History.&nbsp; Even though we did not have kids, we loved geeking out on the dinosaur bones.&nbsp; Getting to eat lunch regularly&nbsp; on The Highline was relaxing during long summer days.&nbsp; Watching the Macy&rsquo;s Thanksgiving Day Parade was a long time childhood dream, and going to the balloon filling party the night before outside our door made it even more special.&nbsp; We also did a lot of touristy things such as visiting The Statue of Liberty and Ellis Island.&nbsp; Best of all, dragging Kathryn to see the ball drop on New Years Eve freezing, standing on a pizza box to stay warm was hysterical. She hated every minute up until the last 10 seconds. &nbsp;</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-parade.JPG %}</p>
<p>Together, all of these events added up to be a life changing experience that we would not trade for the world. &nbsp;</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-subway.JPG %}</p>
<p><strong><em>By Kathryn...</em></strong></p>
<p>For me, living and working in the city was a victory lap to conclude a race that I started ten years before. When I graduated from high school, my only objective was to get the hell out of my small town and do something amazing. I took off for New York after I was accepted to New School University, but I wasn&rsquo;t ready for the path that would be set before me. I returned back to Maine to finish my degree after only three semesters, feeling deflated about my whole experience. When the opportunity arose to return to the city to finish what I started many years ago, I know that I had to give it one more shot.</p>
<p>It&rsquo;s funny how life will give you what you want, but not all at the same time. When I was 18 years old, I felt entitled to a big cushy job where I could be paid enough to make the city my own, while doing what I love. In my second go around, I got exactly that. This time, I had the privilege of making a life with someone that I love.</p>
<p>New York will always hold a special place in my heart. Chris and I got married here. We got our marriage license at NYC City Hall. I took him to the Metropolitan Opera at Lincoln Center for his birthday. We held hands and went ice skating in Rockefeller Center. We spent Christmas Day walking down 5th avenue and catching the last glimpses of the famous holiday windows. We also spent many hours running around the Central Park loop, dreaming of the life that we were just starting to build together. I&rsquo;m glad I never achieved my dreams in my first NYC journey. I learned that it&rsquo;s more fun with someone to share it with.&nbsp;</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-irishpub.JPG %}</p>
<p><strong><em>By Chris...</em></strong></p>
<p>If you know me, you know I like to &ldquo;rant&rdquo; at times.&nbsp; I have always believed that being honest doesn&rsquo;t waste time, however, I have made a promise to myself recently to tailor the message to the desired audience.&nbsp; With that said, Manhattan was a journey back to a major city for me, it was nothing new.&nbsp; I grew up in and around Chicago so I knew what to expect, both the good and the bad.&nbsp; When I left Chicago for Boulder, Colorado I never imagined heading back East ever.&nbsp; I love my wife and when her work came calling &nbsp; what was a good man to do? I had to go.&nbsp; I buckled up and dove in head first selling what I had in Boulder and headed back into the depths of hell I ran so far away from. This time around, however, I learned more about me, and a better understanding of why I left Chicago for Boulder in first place. &nbsp; &nbsp;</p>
<p>I have come to learn that people like what they like and that even though there are parts of the island that I love, I would rather not listen to John Lock and get off for good. It&rsquo;s just not for me.&nbsp; NYC taught me to appreciate nature, more so, than I have ever had before.&nbsp; People that say oh get on a train and just head North to the mountains have either never lived here or didn&rsquo;t have a full time job.&nbsp; I like space, the smell of trees after a morning rain, snow and the people who love it when it falls in buckets, but most importantly peace and quiet.&nbsp; Silence is impossible in NYC.&nbsp; No matter what time of day or night there is just noise, everywhere.&nbsp; NYC has amazing food, just like Chicago, but I loved the farmer&rsquo;s markets of Boulder, not only how easy and pleasant the experiences there were, but the cost.&nbsp; They were far&nbsp; cheaper.&nbsp; The hardest part of the East for me was being a geek.&nbsp; Geeks here are second class citizens.&nbsp; We are not the coolest thing in town, finance and fashion are.&nbsp; I love my t-shirts, I love flannels and normal everyday clothes but most importantly I value my work more than how I dress.&nbsp; I have said the East goes out of it&rsquo;s way to make sure the socioeconomic class system of our country stays in place.&nbsp; Experiencing this first hand was quite alarming and far worse than Chicago.&nbsp; I am a capitalist but I believe in helping anyone in business, not just my set of elite friends that I went to Harvard with who all wear the same polo shirt.&nbsp; Out West there is a sense of community values, where geeks in a coffee shop like Atlas Purveyors could raise their hand with CSS questions and get answers.&nbsp; Not from google, but from people who actually write code and design everyday.&nbsp; The Western geeks are not jailed to co-working spaces, private clubs, or meetups that always cost money.&nbsp; Is NYC technology hot, yes, but I believe you can start a tech startup anywhere nowadays.&nbsp; Most importantly, if you have a solid product, something worth buying, money will find you.&nbsp; In Chicago I almost left code to be a trader and I have seen first hand how the markets work, it&rsquo;s actually a hobby I hope to pursue further one day.&nbsp; There are always winners and losers in every market and you do not need to live in a certain city to have your business be a winner.&nbsp; This may all sound like a rant, and yes a tid bit on the negative side, but not all of my time here was like jail. &nbsp;</p>
<p>Kathryn and I were married here, in Queens actually, something I could have never planned.&nbsp; NYC taught me to appreciate automation, to be efficient with my time, and to focus on what gives me the best ROI, not only in business, but in life.&nbsp; The times that Kathryn and I shared here make me smile, especially the art museums.&nbsp; Since part of Kathryn&rsquo;s family is from the East I have been lucky enough to travel to Maine.&nbsp; To eat home made lobster roll sandwiches, to smell the ocean, and smell the salt water smashing the Northeastern coast.&nbsp; Recently we visited her friend in rural Maine where I had the chance to eat smores, which I hadn&rsquo;t had since I was a little kid.&nbsp; Most importantly though, I was able to see the stars.&nbsp; I believe that too many people have forgotten what stars actually look like, and how small they make you feel.&nbsp; At the end of the day, NYC has taught me to appreciate the finite amount of time we all have in this world.&nbsp; Who we chose to spend it with, what we chose to work on, where we chose to visit all take from the fixed pool of minutes we have.&nbsp; I am thankful for my experiences here, but I more thankful for getting to experience them with the love of my life.</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-XMASTree.JPG %}</p>
<p><strong><em>Bye Bye NYC...</em></strong></p>
<p>The Houghs are leaving Manhattan on the next big adventure of our lives together.&nbsp; No we are not broadcasting where, and if you know already, consider yourself a member of the VIP Club Hough where the best underground house and techno is played 24/7.&nbsp; As one of our good friends would like to say &ldquo;oooh maan, it&rsquo;s time to partay..&rdquo;&nbsp;</p>
<p>{% img /content/since-we-made-it-here-we-can-make-it-anywhere-liberty.JPG %}</p>
<p>Thank you Gotham.</p>
